batch_443/05_Rails/02_Models_and_CRUD/Livecode/lost_pets/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pets
end

batch_443/05_Rails/02_Models_and_CRUD/Livecode/lost_pets/app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = %w[dog cat rabbit snake turtle]

  validates :name, presence: true
  validates :species, inclusion: {
    in: SPECIES
  }

  def since_found
    days = (Date.today - found_on).to_i
    if days == 0
      'today'
    else
      "#{days} days ago"
    end
  end
end

batch_443/05_Rails/02_Models_and_CRUD/Livecode/lost_pets/app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :find_pet, only: %i[show edit update destroy]

  def index
    @pets = Pet.all
  end

  def show; end

  def new
    # TO Return the HTML with the Form
    @pet = Pet.new
  end

  def create
    # Receive the data from the form, and will create a record
    @pet = Pet.new(strong_params)
    @pet.found_on = Date.today
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render :new
    end
  end

  def edit
    # TO Return the HTML with the Form
  end

  def update
    # Receive the data from the form, and will create a record

    @pet.update(strong_params)

    redirect_to pet_path(@pet)
  end

  def destroy
    @pet.destroy

    redirect_to pets_path
  end

  private

  def find_pet
    @pet = Pet.find(params[:id])
  end

  def strong_params
    params.require(:pet).permit(:name, :address, :species)
  end
end

batch_443/05_Rails/02_Models_and_CRUD/Livecode/lost_pets/app/helpers/pets_helper.rb
module PetsHelper
end

batch_443/05_Rails/02_Models_and_CRUD/Livecode/lost_pets/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

batch_443/05_Rails/02_Models_and_CRUD/Livecode/lost_pets/app/views/pets/_form.html.erb
<%= simple_form_for (pet) do |form| %>
<%= form.input :name %>
<%= form.input :address %>
<%= form.select :species, collection: Pet::SPECIES %>
<%= form.button :submit, class: 'btn btn-primary' %>
<% end %>

batch_443/05_Rails/02_Models_and_CRUD/Livecode/lost_pets/app/views/pets/edit.html.erb
<%= render('form', pet: @pet) %>

batch_443/05_Rails/02_Models_and_CRUD/Livecode/lost_pets/app/views/pets/index.html.erb
<div class="container">
  <h1>Lost pets</h1>
  <ul>
    <% @pets.each do |pet| %>
    <li><%= link_to pet.name, pet_path(pet) %> - found <%= pet.since_found %></li>
    <% end %>
  </ul>
</div>

batch_443/05_Rails/02_Models_and_CRUD/Livecode/lost_pets/app/views/pets/new.html.erb
<%= render 'form', pet: @pet %>

batch_443/05_Rails/02_Models_and_CRUD/Livecode/lost_pets/app/views/pets/show.html.erb
<h1><%= @pet.name %> (<%= @pet.species %>) </h1>
<p>Found <%= @pet.since_found %> at <%= @pet.address %></p>


<%= link_to 'Edit', edit_pet_path(@pet) %>
<%= link_to 'Delete', pet_path(@pet), method: 'delete', data: { confirm: 'Are you sure to delete?' } %>